### ISSUE TITLE
Add Whisker menu plugin

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#26]
Please add the whisker menu plugin, as I'm doing testing on that. thanks.

**Comment by ochosi** [comment]
That's already built in the container, just not part of the default upstream panel layout (which is used in the container) because we can't rely on its availability in distros.

**Comment by philipzae** [comment]
I saw it listed as if it was in the container, but when I tried switching to the xubuntu 18.04 panel profile, it didn't show up, and its not listed in the add new items dialog. I tried to add it both in the 20.04 and 18.04 containers.

![image](https://user-images.githubusercontent.com/4412114/88273090-b5a31980-ccea-11ea-89d0-bbc5db942b52.png)

**Comment by JCGoran** [comment]
From what I can tell, this is because Whisker menu is looking for `xfce4-panel` in `/usr/local/bin` (default according to the [cmake docs](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html)), whereas in the container, `xfce4-panel`'s location is `/usr/bin`.

A workaround is to rebuild `xfce4-whiskermenu-plugin` using:
```bash
cmake -DCMAKE_INSTALL_PREFIX=/usr
sudo make install -j
```
and then restart the panel via `xfce4-panel -r`, then the plugin should be visible in the "Add new items" window.

**Comment by philipzae** [comment]
whisker menu still didn't show up in ubuntu_20.04
